### ISSUE TITLE
GE: error deploying k8s

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#746] opened 2020-05-26 16:08 UTC
whats wrong here?

https://explorer.grid.tf/explorer/reservations/9658

"could not set up tap device: could not add tap device: Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy"

**Comment by zaibon** [comment] 2020-05-27 07:03
Most probably this: https://github.com/threefoldtech/zos/issues/585

**Comment by joefoxton** [comment] 2020-06-25 16:01
@hteibler Let's close this as a duplicate of threefoldtech/zos#585

**Closed** 2020-06-25 20:27 UTC
Labels: type_bug
