### ISSUE TITLE
Release 3bot connect v1.3.1 [development_threebot]

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#447] opened 2019-12-02 16:47 UTC
Release next version of 3bot connect

@MathiasDeWeerdt and @DylanVerstraete are doing last bugfixes on Android and iPhone, @azertyalex is testing:
- [x] Android version  ( 1 bug left - need URL )
- [x] Android version  test

- [x] iPhone version
- [x] iPhone version test

UI change still to be done, @DylanVerstraete is doing this:
- [x] UI Adjusted, mobile sign up only

We need a few upgrades for FFP so community can use it more fluently:
@Hamdy 
- [x] Issues FreeFlowPages 
 - https://github.com/freeflowpages/home/issues/6 
 - https://github.com/freeflowpages/home/issues/5
 - https://github.com/freeflowpages/home/issues/4
 - https://github.com/freeflowpages/home/issues/3 

We need a threebot with chatbot  (currently no implementations yet) on '/' running on chatbot.threefold.io. @xmonader will take care of this. @delandtj can change DNS

- [ ] Chatbot online

**Comment by azertyalex** [comment] 2019-12-02 17:15
## Remarks
When opening the app (unregistered) there is weird UI (debatable) due to bottom rounded corners.

"More functionality will be added soon" sticks to bottom. More spacing?

## Bugs 
### 1. Chatbot infinite loading screen
### 2. Bottom bar is greyed out/disabled/unclickable
steps to reproduce unknown
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/9082988/69977833-c7ea0080-152b-11ea-805b-ac76e3cdbb47.png)

</details>

### 3. login attempt not cleared when pressing back button
#### What happens
user goes to ffp and logs in, gets redirected to ffp. User presses back button and sees emoji but can not log in anymore.
#### What should happen
Login attempt should not exsist/be cleared.

### 4. Sometimes Webview keeps loading
Restart app to fix
### 5. Sometimes get service unavailable when opening webview
### 6. UI glitch
When getting a "service unavailable" popup, my webview did pop'ed but went open again causing weird glitch
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/9082988/69979878-6c217680-152f-11ea-938e-04da98e985f3.png)

</details>

**Comment by azertyalex** [comment] 2019-12-02 17:24
About the weird errors:
Seems my staging ffp account is 'broken'. This causes ffp to give some weird/bad responses back to the app, which can not handle those properly, which causes these errors. Better error handling will fix these issues I think.

**Comment by DylanVerstraete** [comment] 2019-12-03 09:53
Remarks:

1. Chatbot infinite loading screen : This is because the current chatbot url is not working. This needs to be changed to a url where the chatbot is a working staging application. No errors can be handled in this case...

**Comment by azertyalex** [comment] 2019-12-03 18:18
## Remarks
None 
## Bugs (only android tested)
### 1. ChatBot screen is white

## Non prio bugs
### 1. Broken login when recovering
**Reproduce:**
*Delete account from phone
*Go to ffp
* Login with 3bot
* Type in name and click login
* Recover account on phone

When recover is done I get redirected to ffp telling me I took a wrong turn
**What should happen:**
Not the above :p

**Comment by azertyalex** [comment] 2019-12-04 11:11
## Remarks
None 
## Bugs (IOS)
### 1. ffp webview not working
- register account on phone
- validate email
- open any of the freeflow pages
loading takes a while, when it finally loads it says internal server error and you are not logged in
closing and opening the app does not fix this issue
### 2. Remove account from device not working

**Closed** 2019-12-09 15:21 UTC
Labels: priority_major, type_story
