### ISSUE TITLE
TFChain Minimal DAO

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1230] opened 2022-04-28 15:54 UTC
for voting for farming changes
for pricing changes
to lock farming params in for future farming (to support INCA & our large farmers)
 lee / erwan / kds

**Comment by xmonader** [comment] 2022-05-04 07:23
duplicate of https://github.com/threefoldtech/home/issues/1228

**Closed by xmonader** 2022-05-04 07:23 UTC
