### ISSUE TITLE
BCDB 10.3 [development_bcdb3]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#459] opened 2019-12-11 05:52 UTC
## features

- [ ] implement master/slave replication: threefoldtech/jumpscaleX_core#260

to be further defined

**Comment by xmonader** [comment] 2020-01-19 12:09
duplicate of https://github.com/threefoldtech/jumpscaleX_core/issues/260

**Closed by xmonader** 2020-01-19 12:09 UTC
Labels: type_story
