### ISSUE TITLE
personal 3bot on grid (jsng) [development_3botng]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#844] opened 2020-07-14 11:08 UTC
specs see
https://github.com/threefoldtech/home/blob/master/specs/personal%203bot%20on%20grid.md

**Comment by xmonader** [comment] 2020-07-16 10:06
duplicate of https://github.com/threefoldtech/home/issues/839

**Closed by xmonader** 2020-07-16 10:06 UTC
