### ISSUE TITLE
used switches for TFGrid need plugins in Ansible

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1008] opened 2021-01-25 06:54 UTC
see what we need to do to manage our existing switches we support,
we need plugins for ansible so we can manage our full environment with Ansible !

**Comment by xmonader** [comment] 2021-03-04 11:08
duplicate of https://github.com/threefoldfoundation/tf_farmer_management_tools/issues/1

**Closed by xmonader** 2021-03-04 11:08 UTC
Labels: type_feature
