### ISSUE TITLE
GE: Deploying min.io/S3 does not complete

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#685] opened 2020-05-11 14:27 UTC
I created a Network, and imported the details into Wireguard, then attempted deployment of an min.io S3 solution. I tried this on both the Free farm and GreenEdge-Vienna2. Both resulted in a the following screen spinning forever...

![Screenshot 2020-05-11 at 16 16 14](https://user-images.githubusercontent.com/1249806/81573059-49c83a80-93a4-11ea-86dd-ab21772f0960.png)

![Screenshot 2020-05-11 at 16 21 42](https://user-images.githubusercontent.com/1249806/81573073-4df45800-93a4-11ea-99e0-116fce38879a.png)

**Comment by zaibon** [comment] 2020-05-12 09:36
This means one or multiple of the nodes never deployed the workloads. We are tracking the bug at https://github.com/threefoldtech/tfexplorer/issues/62

duplicate of https://github.com/threefoldtech/tfexplorer/issues/62

**Closed by zaibon** 2020-05-12 09:36 UTC
Labels: process_duplicate, type_bug
