### ISSUE TITLE
GE: Node-ID changes on HW change

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#670] opened 2020-05-11 09:10 UTC
If you change some HW on a node to due a HW failure, a new node ID is created
and this means all workloads on the "old" node are  gone and you have a "fresh" node

**Comment by gneumann333** [comment] 2020-05-11 09:36
Some more details:
Real-Live Example:
This Node had a defective SSD:
https://explorer.grid.tf/explorer/nodes/3yjVSkNM5vvpiQ8ey7xJHucHNrNvzkM5rWWASEYNsNQn

After the SSD was Changed the Node is shown as Down in the GEC Cockpit

But there is now a new Node with the same MAC-Adress and the same Node_id_v1:
https://explorer.grid.tf/explorer/nodes/D7NcTCz9JAxS7EMvLf1pJtCgc72ogrFQWfBPkeNWPkaU

With the change of Hardware the Hardware fingerprint changed so the Server was recognized as "new" 
- **How does that effect workloads deployed on the node?**
  Do they get transferred to the new Node-ID?
  Does the Grid User have to redeploy

- **What happens to the Reservation?**
   Tokens are pay till the Node went "down" for repair?

- **How does that effect token earning`s**
   Would the 60 Months be reset?
   With that a Hardware failure threatens our whole earning potential for a node

- **How do we set the old Node to be obsolete in the Cockpit**

**Comment by zaibon** [comment] 2020-05-12 07:56
Duplicate of https://github.com/threefoldtech/zos/issues/438

**Closed by zaibon** 2020-05-12 07:56 UTC
Labels: process_duplicate

**Comment by gneumann333** [comment] 2020-05-23 08:27
@zaibon 
The issue in #438 is a different issue
Jan talks about the case where the actual Keypair of a node is lost.
We observed that a (any) change in Hardware ( in our case replacement Disk or replacement Ram) changed the Node identification

I would put this in relation with this:
[https://github.com/threefoldtech/zos/issues/309]

Alternatively the HPE TPM Module could used for the Keypair

**Comment by zaibon** [comment] 2020-05-23 10:19
> We observed that a (any) change in Hardware ( in our case replacement Disk or replacement Ram) changed the Node identification

Are you sure you have seen modification of the node ID after a ram replacement with 0-OS v2 ?
Cause that should not be the case. Disk replacement could cause this is the disk replaced was the one storing the identity of the node. But this is the only case where any hardware replacement would impact the node identity.
