### ISSUE TITLE
mastodon deployable on tf playground

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1326] opened 2022-11-09 15:28 UTC
- [ ] mastodon weblet
- [ ] deployable on tfplay as part of 3.8
- [ ] documentation on how to deploy on manual

https://github.com/threefoldtech/grid_weblets/issues/1080

**Comment by xmonader** [comment] 2022-11-09 15:58
closing duplicate of https://github.com/threefoldtech/grid_weblets/issues/1080

**Closed by xmonader** 2022-11-09 15:58 UTC
Labels: type_story
