### ISSUE TITLE
js_ng v0.9 released

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#706] opened 2020-05-16 06:18 UTC
## requirements

- [ ] integrated with docker builders
    - [ ] usable as library on / (not as sandboxed env) on docker
- [ ] wizards run with state 
    - [ ] run behind bottle server in example script
- [ ] all required tfgrid sal's ported
- [ ] stellar client ported
- [ ] job engine (specs see Kristof)
    - question: asyncio of gevent process mgmt ?
    - need to agree on data model for job, log, alert

## not to do yet

- no packages
- no full blown 3bot server yet

**Comment by xmonader** [comment] 2020-05-26 08:14
duplicate of https://github.com/threefoldtech/home/issues/671

**Closed by xmonader** 2020-05-26 08:14 UTC
