### ISSUE TITLE
GE: Wallet Manager in SDK browser can't handle multiple administrators

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#808] opened 2020-06-23 13:43 UTC
After adding greenedgeagent.3bot as an administrator, the wallet management screen cleared. Now when I try to restore wallets to it, I get the message "Could not import wallet" for any wallet. The same wallets work fine elsewhere.

Maybe related: 5 minutes prior to seeing this problem, I experienced a problem launching the SDK browser. This is the sequence of events:
1. Logged in as joefoxton.3bot
2. Added greenedgeagent.3bot as an adminsrator
3. Logged out as joefoxton.3bot
4. Everything worked fine, as expected (including wallet manager)
5. Stopped threebot, exited SDK, logged out, restarted machine (for other reasons)
6. Logged back in as greenedgeagent, started SDK
7. Could not open threebot browser
8. Rebooted again
9. Ran "threebot restart" - took a solid 5 minutes to complete
10. Now I could run "threebot browser" and all worked fine... except the wallet management as seen below.

![Screenshot 2020-06-23 at 15 39 39](https://user-images.githubusercontent.com/1249806/85410780-ca638480-b567-11ea-8fc3-38734250da6b.png)

![Screenshot 2020-06-23 at 15 39 46](https://user-images.githubusercontent.com/1249806/85410798-ce8fa200-b567-11ea-9193-067e4eb29a11.png)

**Comment by BolaNasr** [comment] 2020-06-24 08:50
Hello @joefoxton 
i tried your scenario and all works fine
i add ```waleedhammam.3bot``` as administrators
![image](https://user-images.githubusercontent.com/10259267/85524086-1534d900-b608-11ea-9916-9e5f5c0406fd.png)
Then check my wallets
![image](https://user-images.githubusercontent.com/10259267/85524204-3bf30f80-b608-11ea-9158-201d25d77dc1.png)
Then logged out and restart my Threebot server and login again using ```waleedhammam 3bot```
i saw all my wallet in his admin dashboard 

![image](https://user-images.githubusercontent.com/10259267/85523897-d3a42e00-b607-11ea-8ba9-3a7274590d95.png)

**Comment by grimpy** [comment] 2020-06-24 08:52
@joefoxton can you check when loading the wallets if you get new errors in the alerts interface and post it here if so?

**Comment by joefoxton** [comment] 2020-06-24 11:45
Must be a display issue. Looks like the SDK still has all my wallets (as it should, I didn’t remove them), but can’t display them. This problem is easily replicable over here, on both by machines. Have done multiple restarts of threebot, sdk, machine etc.

EXCEPTION: cannot do new object, Green Edge Agent Wallet exists

--TRACEBACK------------------ {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/Decorators.py in wrapper_action 67 res = func(self, **kwargs) {DIR_BASE}/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/admin/actors/wallet.py in import_wallet 77 wallet = j.clients.stellar.new(name=name, secret=secret, network=network) {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in new 25 raise j.exceptions.Base(f"cannot do new object, {name} exists") ——————————————

Screen is still stuck here

**Comment by grimpy** [comment] 2020-06-24 11:50
@joefoxton thank you for the extra information but the alert you pasted is not the one I'm looking for I was hoping to find something during the listing, the one you pasted is the one about the import failing (which makes sense since the wallets are in fact still there).

Could you have another look if you can find something related to listing of wallets? (make sure to redact all kind of wallets secrets before pasting here)

**Comment by joefoxton** [comment] 2020-06-24 12:43
Which one do you need?

**Comment by grimpy** [comment] 2020-06-24 13:11
Anything that has references to `https://localhost:4000/zerobot/admin/actors/wallet/get_wallets`

if you could check in the 'inspect' of your browser if this specific call returns an error that could be helpfull aswell

**Comment by joefoxton** [comment] 2020-06-24 13:51
Yeah, lots of errors on get_wallets...

[localhost-1593006654722.log](https://github.com/threefoldtech/home/files/4825755/localhost-1593006654722.log)

**Comment by joefoxton** [comment] 2020-06-24 13:58
Please also note, I'm unable to use Solution Expose. Maybe related? https://github.com/threefoldtech/home/issues/810

**Comment by grimpy** [comment] 2020-06-24 14:01
:4000/zerobot/admin/actors/wallet/get_wallets:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

This is the only usefull line really, it would be nice if you could send the output date from inspect network tab response.

is `wallets = j.clients.stellar.find()` working inside the kosmos shell?

**Comment by joefoxton** [comment] 2020-06-24 14:15
Invalid Secret Seed is the error
(Please don’t print out our secrets in clear text!)

**Comment by grimpy** [comment] 2020-06-24 14:26
@joefoxton this is an indication that atleast one of your wallets was imported with an invalid secret, that seed being printed is not correct.

this effectively makes this a duplicate of this
https://github.com/threefoldtech/jumpscaleX_threebot/issues/760

**Comment by joefoxton** [comment] 2020-06-24 14:28
Why would that stop all my wallets from being displayed?

Why would the import have succeeded? Why not show an error message there?

Is there a way to remove the wonky wallet so I can move ahead with reservations & wallet management?

**Comment by joefoxton** [comment] 2020-06-24 14:30
Also - PLEASE do not display even incorrect wallet secrets… they might be one character away from the right one

**Comment by grimpy** [comment] 2020-06-24 14:41
@joefoxton yes you are right and that is fixed as part of that other issue I just linked.
In version 10.6 it's not very straightforward to get the wrong wallet. but you can try the following:

in kosmos shell (when threebot server is stopped)
```
for wallet in j.data.bcdb.system.models.jumpscale__stellar__client.find():
    try:
         j.clients.stellar.get(wallet.name)
    except:
         print(f"Broken wallet {wallet.name}")
# now if you are convinced those wallets are indeed broken and are ok with deleting them do the following
j.data.bcdb.system.models.jumpscale__stellar__client.get_by_name("<wallet name here>t").delete()
```

The actions above you are basicly operating on db level instead of application level

**Comment by joefoxton** [comment] 2020-06-24 14:49
Yep, “Green Edge Wallet” is broken. But when I run the delete…

**Comment by grimpy** [comment] 2020-06-24 15:14
@joefoxton as mentioned in my previous comment
you need to run it when threebot server is stopped
so
3sdk threebot shell
```
3bot stop
kosmos -p
jsx>j.data.bcdb.system.models.jumpscale__stellar__client.get_by_name("Green Edge Walle").delete()
jsx>exit()
3bot start
```

**Comment by joefoxton** [comment] 2020-06-24 15:24
I’m on Mac OS.. no scrolling I’m afraid

Will try the shift

**Comment by grimpy** [comment] 2020-06-24 15:48
@joefoxton I beleive the last comment belongs to another issue, Did you manage to get around the problem in this issue, I would like to close it as duplicate

**Comment by joefoxton** [comment] 2020-06-25 07:27
Ok, so the fix worked… however…

1. The commands you sent were not right on my side. FYI are the commands I ran:

In a Mac terminal:
./3sdk_v10.6_darwin_x86_64
3sdk> threebot stop
3sdk> container kosmos
JSX> j.data.bcdb.system.models.jumpscale__stellar__client.get_by_name("Green Edge Agent").delete()
JSX> exit ()
3sdk> threebot restart
3sdk> threebot browser

2. What’s the root cause? How did we get into this situation? Is that problem now fixed?

Joe

**Closed** 2020-06-25 08:17 UTC
