### ISSUE TITLE
extracting TFGrid Stats from explorer

### ISSUE THREAD

**Issue by renauter** [threefoldtech/home#1213] opened 2022-04-14 12:59 UTC
- Read only view from FULL network
- Not part of the admin portal
- Nodes / Map (maybe new one)
- Purpose is just to show how big our network is and how it's growing
- Should be easy for people to integrate in multiple websites
- This is not explorer

**Comment by xmonader** [comment] 2022-04-14 14:39
duplicate of https://github.com/threefoldtech/home/issues/1200

**Closed by xmonader** 2022-04-14 14:39 UTC
